---

- 
  name: Install unzip
  apt:
    name: unzip
    state: present
- 
  name: Create Tools directory if it does not exist
  ansible.builtin.file:
    path: '~/Tools'
    state: directory
    mode: '0755'

- name: Download AWS cli
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: '~/Tools/awscliv2.zip'

- name: Unarchive the jdk tar file if it is not extracted
  unarchive:
    src: '~/Tools/awscliv2.zip'
    dest: '~/Tools/'
    remote_src: yes
    list_files: yes
  register: unarchive_awscli

# - debug:
#     var: unarchive_res_java

- name: cd into 
  shell: install.sh 
  args:
    chdir: ~/Tools/"{{unarchive_awscli.files[0].split("/")[0]}}"/


